# Generated by Django 6.0.6 on 2026-07-02 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('filiere', models.CharField(choices=[('IA', 'Intelligence Artificielle'), ('IM', 'Ingénierie Mathématique'), ('GL', 'Génie Logiciel'), ('SE_IOT', 'Systèmes Embarqués & IoT'), ('SI', "Systèmes d'Information")], max_length=10)),
                ('niveau', models.CharField(help_text='Ex: Licence 2, Licence 3, Master 1', max_length=50)),
                ('format_mentorat', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('les_deux', 'Présentiel & En ligne')], default='les_deux', max_length=15)),
                ('matieres', models.ManyToManyField(related_name='mentors', to='matching.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='matching.mentor')),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
            },
        ),
    ]
